### ISSUE TITLE
Using llvm_asm is nightly instead of stable

### ISSUE THREAD

**Issue by mscofield0** [Ravenslofty/prussia#7]
I read some comments in the code and you seem to want to be able to run it on the stable toolchain. Maybe change that?

**Comment by Ravenslofty** [comment]
`asm!` is not supported for the versions of MIPS that the PS2 uses, thus we have to use `llvm_asm!` instead. I don't think upstream cares very much about the PS2 as an architecture, and anything else that might use old MIPS versions like this is hopelessly obsolete...

**Comment by mscofield0** [comment]
Any way to link it separately as a file?
